
/*Create a Binary Search algorithm that searchs the data for a hairstyle based on the users input/search 
public class algorithm{
public static n/ String BinarySearch(String [] arr, string target){
 String left = "A";
 String right = arr.length - 1;

 while (left <=right) {
    String mid = left + (right-left)/2;
    if (arr[mid] == target) {
        return mid;
    }

    if (arr[mid] < target) {
        left = mid + 1;
    }else{
        right = mid -1;
    }
 }
 return -1
}
}
*/    
