
/*Create Hashmap 
import java.util.HashSet;

Public class Main{

    Public static void main(String []args){
        HashSet<String, String> Hairstyles = new HashSet<String>();
        Hairstyles.add("Weave");
        Hairstyles.add ("Braids");

        System.out.println(Hairstyles);
    }
}

/*
/*Create customer base*/
/*Defining Class
public class Customer{
    public static String STATUS = "Membership";
/*Adding attributes 
    String firstname;
    String lastname;
    String status;

public Customer(String firstname, String lastname, String status){
    this.firstname = firstname;
    this.lastname = lastname;
    this.status = status;
}
   
System.out.println("Welcome " + firstname + lastname + "You are currently a " + status);

}

/*Creating instances of the customer class 

public class CustomerBase
public static void main(String []args){
Customer Member = new Customer (firstname: "Sarah", lastname: "Jones", status:"Member");
Customer NonMember = new Customer (firstname: "Sarah", lastname: "Jones", status:"Non-Member");
}
 

 public String getDetails (){
    String details = String.format(
        "Welcome %s %s, You are currently a %s"
        this.firstname, this.lastname, this.status, STATUS
    );
    return details;
 }
*/

